### ISSUE TITLE
Wondering how you got the target values in 'BRPeerManager.m' near block hash, timestamp.

### ISSUE THREAD

**Issue by losh11** [peritus/doughwallet#1]
Can you show how you did this for Doge and how I could possibly do this for LTC?
Thanks.

**Comment by peritus** [comment]
Could you point out the line (link will do) you're referring to ?

**Comment by losh11** [comment]
doughwallet/BreadWallet/BRPeerManager.m
Line 93 and the ones below.
Where it says 0x01010000u (that being the target)...

How did you get that, can't find anything like it for LTC. And would you mind saying how you did it for DOGE.

**Comment by peritus** [comment]
Here's the script to get the checkpoints from your local dogecoin node: https://github.com/peritus/doughwallet/blob/7dca34b40c1def4743fda342f1b1d5605850e572/get_checkpoint_array.py .. you should be able to adapt that to ltc easily.

Please re-open if that doesn't answer your question.
