### ISSUE TITLE
passcode keyboard didn't show up on iOS9

### ISSUE THREAD

**Issue by nolith** [peritus/doughwallet#2]
Hello
in iOS9 when clicking unlock the passcode prompt will show up without the keybord.
Pressing cancel will make it appear for just a few seconds.

**Comment by peritus** [comment]
Fixed in 1de0bfa02122d744c82fa61801257102795f7b98.

Also submitted for AppStore review (might take a week). 

If you want to get your hands this earlier via TestFlight, send me an email.

**Comment by nolith** [comment]
Thank you,
I wrote you my testflight email to doughwallet-support@codefrosting.com

@ChangeTip, send a beer to @peritus

**Comment by changetip** [comment]
Hi @codefrosting, @nolith sent you a tip worth a beer (15,031 bits/$3.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/897501)**.

**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by nolith** [comment]
Sound's like it gets confused by the email address... 
@ChangeTip, send a beer to @peritus

**Comment by changetip** [comment]
Hi @peritus, @nolith sent you a tip worth a beer (15,046 bits/$3.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/897502)**.

**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by peritus** [comment]
Hey, two beers! Thanks! :beers:
