### ISSUE TITLE
Integration of SolarCoin into breadwallet 

### ISSUE THREAD

**Issue by assaf8200** [peritus/doughwallet#5]
Hello,
my name is Assaf Ben Or and i am from the SolarChange(www.solarchange.co), we are promoting the SolarCoin (www.solarcoin.org) technology and would like to check the possibility that you your development team would help us to integrate breadwallet to SolarCoin. The SolarCoin grants SolarCoins for producing Solar Energy and works on a blockchain very similar to VeriCoin and AltCoin. 
I would be happy if you could contact me, available also in Skype: assaf.ben.or
Kind Regards,
Assaf

**Comment by peritus** [comment]
This is neither a breadwallet nor a doughwallet support forum. This is only for tracking doughwallet issues.
